# Generated by Django 5.2.16 on 2026-08-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        ("jobber", "0007_jobberuser_expertise_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("monthly_goal_pct", "Monthly goal below X%"),
                            ("annual_goal_pct", "Annual goal below X%"),
                            ("completion_rate_pct", "Completion rate below X%"),
                            ("revenue_per_hour", "Revenue/hr below $X"),
                            ("team_avg_revenue_pct", "Revenue below X% of team average"),
                        ],
                        max_length=30,
                    ),
                ),
                ("threshold_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "severity",
                    models.CharField(
                        choices=[("critical", "critical"), ("warning", "warning")],
                        max_length=10,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="jobber.jobberuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "alert rule",
                "verbose_name_plural": "alert rules",
                "db_table": "alert_rules",
            },
        ),
    ]
