# Generated by Django 5.2.16 on 2026-08-21 00:00

from django.db import migrations


class Migration(migrations.Migration):
    """
    Design correction (2026-08-21, confirmed TL) -- AlertRule.user was
    added in 0001 under the original (incorrect) "per-technician rule"
    design. Rules are company-wide policies, automatically evaluated
    against every active technician -- not tied to one named person at
    creation time. Zero real AlertRule rows exist in production yet, so
    this is a clean schema fix, not a data migration.
    """

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertrule",
            name="user",
        ),
    ]
