# Generated by Django 5.2.16 on 2026-07-23 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobber_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(default='bearer', max_length=40)),
                ('scope', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobber_account', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'jobber account',
                'verbose_name_plural': 'jobber accounts',
                'db_table': 'jobber_accounts',
            },
        ),
    ]
