# Generated by Django 5.2.16 on 2026-08-07 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobber", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobberClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("jobber_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "tags_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("synced_at", models.DateTimeField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobber_clients",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "jobber client",
                "verbose_name_plural": "jobber clients",
                "db_table": "jobber_clients",
            },
        ),
        migrations.CreateModel(
            name="JobberJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("jobber_id", models.CharField(db_index=True, max_length=255)),
                ("job_number", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("job_status", models.CharField(max_length=50)),
                ("status_display", models.CharField(max_length=50)),
                (
                    "service_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("jobber_created_at", models.DateTimeField(blank=True, null=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("labour_duration_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "labour_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("synced_at", models.DateTimeField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobber.jobberclient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobber_jobs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "jobber job",
                "verbose_name_plural": "jobber jobs",
                "db_table": "jobber_jobs",
            },
        ),
        migrations.CreateModel(
            name="JobberInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("jobber_id", models.CharField(db_index=True, max_length=255)),
                ("invoice_number", models.IntegerField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("issued_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("invoice_status", models.CharField(max_length=50)),
                ("status_display", models.CharField(max_length=50)),
                ("synced_at", models.DateTimeField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="jobber.jobberclient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobber_invoices",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "jobs",
                    models.ManyToManyField(
                        blank=True, related_name="invoices", to="jobber.jobberjob"
                    ),
                ),
            ],
            options={
                "verbose_name": "jobber invoice",
                "verbose_name_plural": "jobber invoices",
                "db_table": "jobber_invoices",
            },
        ),
        migrations.CreateModel(
            name="JobberSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "running"),
                            ("success", "success"),
                            ("partial", "partial"),
                            ("failed", "failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("clients_synced", models.IntegerField(default=0)),
                ("users_synced", models.IntegerField(default=0)),
                ("jobs_synced", models.IntegerField(default=0)),
                ("visits_synced", models.IntegerField(default=0)),
                ("invoices_synced", models.IntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobber_sync_runs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "jobber sync run",
                "verbose_name_plural": "jobber sync runs",
                "db_table": "jobber_sync_runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="JobberUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("jobber_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("is_account_admin", models.BooleanField(default=False)),
                ("is_account_owner", models.BooleanField(default=False)),
                ("synced_at", models.DateTimeField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobber_users",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "jobber user",
                "verbose_name_plural": "jobber users",
                "db_table": "jobber_users",
            },
        ),
        migrations.CreateModel(
            name="JobberVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("jobber_id", models.CharField(db_index=True, max_length=255)),
                ("synced_at", models.DateTimeField()),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits",
                        to="jobber.jobberuser",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="jobber.jobberjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobber_visits",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "jobber visit",
                "verbose_name_plural": "jobber visits",
                "db_table": "jobber_visits",
            },
        ),
        migrations.AddConstraint(
            model_name="jobberclient",
            constraint=models.UniqueConstraint(
                fields=("tenant", "jobber_id"),
                name="unique_jobber_client_tenant_jobber_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobberjob",
            constraint=models.UniqueConstraint(
                fields=("tenant", "jobber_id"),
                name="unique_jobber_job_tenant_jobber_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobberinvoice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "jobber_id"),
                name="unique_jobber_invoice_tenant_jobber_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobberuser",
            constraint=models.UniqueConstraint(
                fields=("tenant", "jobber_id"),
                name="unique_jobber_user_tenant_jobber_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobbervisit",
            constraint=models.UniqueConstraint(
                fields=("tenant", "jobber_id"),
                name="unique_jobber_visit_tenant_jobber_id",
            ),
        ),
    ]
