# Generated by Django 5.2.16 on 2026-08-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobber", "0002_jobberclient_jobberjob_jobberinvoice_jobbersyncrun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobberjob",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
