# Generated by Django 5.2.16 on 2026-08-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobber", "0003_jobberjob_completed_at"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobberTimeSheetEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("jobber_id", models.CharField(db_index=True, max_length=255)),
                ("final_duration_seconds", models.IntegerField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_entries",
                        to="jobber.jobberjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobber_timesheet_entries",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timesheet_entries",
                        to="jobber.jobberuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "jobber timesheet entry",
                "verbose_name_plural": "jobber timesheet entries",
                "db_table": "jobber_timesheet_entries",
            },
        ),
        migrations.AddConstraint(
            model_name="jobbertimesheetentry",
            constraint=models.UniqueConstraint(
                fields=("tenant", "jobber_id"),
                name="unique_jobber_timesheet_entry_tenant_jobber_id",
            ),
        ),
    ]
