# Generated by Django 5.2.16 on 2026-08-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobber", "0004_jobbertimesheetentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobbervisit",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_visits", to="jobber.jobberuser"
            ),
        ),
    ]
