# Generated by Django 5.2.16 on 2026-08-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobber", "0005_jobbervisit_assigned_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobberuser",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
