# Generated by Django 5.2.16 on 2026-08-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobber", "0006_jobberuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobberuser",
            name="expertise",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobberuser",
            name="experience_years",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
