# Generated by Django 5.2.16 on 2026-08-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        ("jobber", "0005_jobbervisit_assigned_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.DateField()),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_goals",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "team goal",
                "verbose_name_plural": "team goals",
                "db_table": "team_goals",
            },
        ),
        migrations.CreateModel(
            name="TechnicianGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.DateField()),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_goals",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_goals",
                        to="jobber.jobberuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "technician goal",
                "verbose_name_plural": "technician goals",
                "db_table": "technician_goals",
            },
        ),
        migrations.AddConstraint(
            model_name="teamgoal",
            constraint=models.UniqueConstraint(
                fields=("tenant", "month"),
                name="unique_team_goal_tenant_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="techniciangoal",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user", "month"),
                name="unique_technician_goal_tenant_user_month",
            ),
        ),
    ]
