# Generated by Django 5.2.16 on 2026-08-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
        ("tenants", "0001_initial"),
        ("jobber", "0006_jobberuser_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamAnnualGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.DateField()),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_annual_goals",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "team annual goal",
                "verbose_name_plural": "team annual goals",
                "db_table": "team_annual_goals",
            },
        ),
        migrations.CreateModel(
            name="TechnicianAnnualGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.DateField()),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_annual_goals",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_goals",
                        to="jobber.jobberuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "technician annual goal",
                "verbose_name_plural": "technician annual goals",
                "db_table": "technician_annual_goals",
            },
        ),
        migrations.AddConstraint(
            model_name="teamannualgoal",
            constraint=models.UniqueConstraint(
                fields=("tenant", "year"),
                name="unique_team_annual_goal_tenant_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="techniciannualgoal",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user", "year"),
                name="unique_technician_annual_goal_tenant_user_year",
            ),
        ),
    ]
